name: burn
version: 1.4.0
main: xyz.censera.burn.Burn
api-version: '1.21'
description: ' '
authors: []
soft-depend:
  - floodgate

commands:
  burn:
    description: ' '
    usage: ' '
    permission: burn.use
    permission-message: ''

permissions:
  burn.use:
    description: ' '
    default: op
